name: .NET 5 Build and SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        organization: Pasha
        projectKey: SimpleDbDocs
        projectName: SimpleDbDocs
        extraProperties: >
          sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
          sonar.coverage.exclusions=**/*Tests*

  sonarcloud-check:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: SonarCloud Quality Gate
      uses: SonarSource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.organization=Pasha
          -Dsonar.projectKey=SimpleDbDocs
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.qualitygate.wait=true